{% set python_min = "3.10" %}
{% set name = "pygeoapi" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygeoapi-{{ version }}.tar.gz
  sha256: 43689d6c89e6bd7536c9384db4617fa499f82823394a656dd50c2ea126c92150

build:
  entry_points:
    - pygeoapi=pygeoapi:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - babel
    - click
    - filelock
    - flask
    - jinja2
    - jsonschema
    - pydantic
    - pygeofilter
    - pygeoif
    - pyproj
    - python-dateutil
    - pytz
    - pyyaml
    - rasterio
    - requests
    - shapely
    - sqlalchemy
    - tinydb

test:
  files:
    - local.config.yml
  commands:
    - pip check
    - export PYGEOAPI_CONFIG=local.config.yml
    - pygeoapi --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pygeoapi.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: pygeoapi provides an API to geospatial data

extra:
  recipe-maintainers:
    - tomkralidis
    - ocefpaf
    - DManowitz
